### ISSUE TITLE
cannot find wg binary in mac bigsur

### ISSUE THREAD

**Issue by bikramtuladhar** [k4yt3x/wg-meshconf#15]
```
which wg
```
Response:
```
/usr/local/bin/wg
```

Adding peer
```
wg-meshconf addpeer Name --address 10.1.0.1/16 --endpoint xx.xx.xx.xx
```
Response:
```
Traceback (most recent call last):
  File "/usr/local/bin/wg-meshconf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/wg_meshconf/wg_meshconf.py", line 161, in main
    args.saveconfig,
  File "/usr/local/lib/python3.7/site-packages/wg_meshconf/database_manager.py", line 120, in addpeer
    privatekey = self.wireguard.genkey()
  File "/usr/local/lib/python3.7/site-packages/wg_meshconf/wireguard.py", line 47, in genkey
    stdout=subprocess.PIPE,
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python@3.7/3.7.9_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/wg': '/usr/bin/wg'
```

**Comment by k4yt3x** [comment]
wg-meshconf defaults wg's path to be `/usr/bin/wg`, and I assume you already have that figured out.
Instead of providing an option to specify wg binary's location, I'm thinking maybe I can just embed wg's pubkey and privkey function directly into the script to break the external dependency.

**Comment by k4yt3x** [comment]
I was able to remove the script's external dependency on the wg binary. Update the package and you should be able to use it without wg at all.
Also thanks to @dimon222's help which made things a lot easier.

**Comment by bikramtuladhar** [comment]
thank you @k4yt3x and @dimon222
