### ISSUE TITLE
Error with csv

### ISSUE THREAD

**Issue by RobertusIT** [k4yt3x/wg-meshconf#37]
[database.csv](https://github.com/k4yt3x/wg-meshconf/files/12407900/database.csv)
```
root@debian:~# wg-meshconf init
Traceback (most recent call last):
  File "/usr/local/bin/wg-meshconf", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/wg_meshconf/wg_meshconf.py", line 144, in main
[database.csv](https://github.com/k4yt3x/wg-meshconf/files/12407899/database.csv)

    database_manager.init()
  File "/usr/local/lib/python3.9/dist-packages/wg_meshconf/database_manager.py", line 98, in init
    database = self.read_database()
  File "/usr/local/lib/python3.9/dist-packages/wg_meshconf/database_manager.py", line 134, in read_database
    elif KEY_TYPE[key] == list:
KeyError: 'Name;Address;Endpoint;AllowedIPs;ListenPort;PersistentKeepalive;FwMark;PrivateKey;DNS;MTU;Table;PreUp;PostUp;PreDown;PostDown;SaveConfig'
```

**Comment by k4yt3x** [comment]
It looks like an issue with how you saved the CSV file. Set the separators to comma.
